version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: fimoney-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: fimoney
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - fimoney-network

  # Node.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fimoney-app
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://admin:password123@mongodb:27017/fimoney?authSource=admin
      JWT_SECRET: your-secret-key-here
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - fimoney-network
    command: npm run dev

volumes:
  mongodb_data:
    driver: local

networks:
  fimoney-network:
    driver: bridge
